project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: XIVLauncher/Resources/Loc/XIVLauncher_Localizable.json
    translation: XIVLauncher/Resources/Loc/xl/xl_%two_letters_code%.json
